return 0;}
printf("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM>MMMMMMMM'MMMMMMMMMMMM");printf("\n");
printf("MMMMMMx*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?MMMMMMMMMMMMMMMMM\\MMMMMMMM'MMMMMMMMMMMM");printf("\n");
printf("MMMMMMMMx*MMMMMMMMMMMMMMMMMMMMMMMMMMMM#xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");printf("\n");
printf("MMMMMMMMMM(MMMMMMMMMMMMMMMMMMMMMMMMM*xMMMMMMMMMMMMMMMMMMMMMMMMMMMM:MMMMMMMMMMMMM");printf("\n");
printf("MMMMMMMMMMMM\"MMMMMMMMMMMMMMMMMMMMMM\"MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\\MMMMMMMMMMMMMM");printf("\n");
printf("MMX*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM)MMMMMMMMMMMMMMM");printf("\n");
printf("*MMMHMMMMMMMMMMMMMMM*******\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"*\"\"\"\"***MMMMMMMMMMMMM:MMMMMMMMMMMMMMMM");printf("\n");
printf("Mn?MMMM\"`         ....:::===:::::........   .x!MSXMMMX    `MM\"*MMMMMMMMMMMMMMMMM");printf("\n");
printf("*MMMMM      `                          .HXMMSX!XSX!MMMMx  /M!       `\"\"*MMMMMMMM");printf("\n");
printf("MMMMMM                                dX!XSX!XSX!XSMMMSXh.MM               `\"\"MM");printf("\n");
printf("**MMMM                               MSX!XSX!XSX!XMMMMSXHMSX! `\"~+..");printf("\n");
printf("MM\"MMf                               X!XSX!XSX!XSMMMMMHMSX!XSX        ^\"=..");printf("\n");
printf(")HMMM                               'X!XSX!XSXHMMMMMMMMMSX!XSM              ^~:.");printf("\n");
printf("MMMMM                                MSX!XMMMMSXMMMM!XSX!XSX!~==:...");printf("\n");
printf("MMMMM            ......              .MMMMSX!MSXHMMX!XSX!XSP*+x.      `\"\"~=::..");printf("\n");
printf("MMMMM        .=\"            ```^\"\"\"!!*-*M*tXSX!XMMMXSX!XSXf      `\"*+x.");printf("\n");
printf("MMMMX   .+~`  ..::::+=======~~~~~n\%!:.X..  `*X!MMM!XSX!X\"               `\"*%cx..",'%');printf("\n");
printf("MMMMM~\" .xnMHX                 .\" \" `       ``\"MMM\"MX. `\"\"-=:..                \"");printf("\n");
printf("MMMMMf\" 'MM~M~         ...x.   \"              'MMX      `\"~=:..  `\"+.");printf("\n");
printf("MMMMMX   MxMM     '\"\"```` `\"MMMHx.            XMM                )MH:.`~+.");printf("\n");
printf("MMMMMX   MM.!                  `\"*MMMh.       XMM           .xHMM*\"   `\".  `~+.");printf("\n");
printf("MMMMMM  / HM           '!!XXXXXXXX!:: '.      MMM        :MMM*\" .....::.  `~:.");printf("\n");
printf("XMMMMM \".?MM            MM***MMMHXX^\"XX!x     MMX       x::!XXHHHHHHHHHh      MM");printf("\n");
printf("XMMMMM>' 'MM            'Mk  !!MM!!\"?x `\"!    !MX      f`  .nMMMMMM\"\"MMM       M");printf("\n");
printf("MMMMMMM  XMM             `Mh  !!!~  ..\\   X    MM     \"  -M^'!!\?\?!!  XMM       4");printf("\n");
printf("MMMMMMM  'MM                 `\"\"\"\"\"            M*k   f  ~.....(!!(..nMM*       '");printf("\n");
printf("MMMMMMMM  MM                               >    M?:                            X");printf("\n");
printf("MMMMMMMMMX?M                               !     M:\"                           M");printf("\n");
printf("MMMM#XMMMX ML                                     M.                           M");printf("\n");
printf("MM*xMM)MMXX?M                                      #:                         'M");printf("\n");
printf("M!MMMMMMX/M-M                                       `:                        XM");printf("\n");
printf("MHMMM>MMX`M !M                                        +                       MM");printf("\n");
printf("MMMMMXMMX`MM`'                                                               MX");printf("\n");
printf("MMMMfMMMX/MM:!                                                              X M");printf("\n");
printf("MMMMMMMMX/MMM !                                                            :!MM");printf("\n");
printf("MMMMMMMMX`?M4> .                                                          .!:MM");printf("\n");
printf("XM*\"\"`  X`'M X  .                       ..                               :: fMM");printf("\n");
printf("        X/'M  :  -                      ^~!!     .x+!                   ~/ / MM");printf("\n");
printf("        X/'M  ':                           '!:.:!~                      ~ /  MM");printf("\n");
printf("        X`'M   `.                            ```                      .` :   MM");printf("\n");
printf("        X`'X     .                                                      .~   MM!");printf("\n");
printf("        X/'X                             .xnh  x..                     .~    MM>");printf("\n");
printf("        X/'!X     !                   xHMMMMMMMMMMMHx                  ~    'MM>");printf("\n");
printf("        X`'!'      !:              +MMMM?????MMMMMMMMMMx.            .~     'MMX");printf("\n");
printf("        X`'!       X!!               `X!!!!!!!!!!!!!!X\"             :       :MMX");printf("\n");
printf("        X/'!        X!!.               `!!!!!!~`` !X\"              /        XMMX");printf("\n");
printf("        X/'!        'X!!x                 ^\"~\%!!*~`               !         XMMX");printf("\n");
printf("        X`'!          !!!!                                      .\"          MMMX");printf("\n");
printf("        X`'!           !!!!x                                   X            MMM?");printf("\n");
printf("        X/'!            !!!!!x                               .!!!x          MMM'");printf("\n");
printf("        X/'!            '!!!!!!x.                          .!!!!!!\?.        MMM'");printf("\n");
printf("        X`'!             `!!!!!!!!:                     .:!!!!!!!!!!!.      MMX'");printf("\n");
printf(".       X`'!              ~!!!!!!X!!%c...           ..:!!!M!!!!!!!!!~``%c     MMX",'%','%');printf("\n");
printf(" \".     X/'!               ~!!!!!!!!!!!!!!!!\?\?\?!!!!!!!!!M!!!!~`         XMMHMMX");printf("\n");
printf("   %c    X/'!                 !!!!!!!!!!!!!!!!!!!!!!!!!X!!!!`           dMMMMMMMM",'%');printf("\n");
printf("    `+  X`'!                   !!!!!!!!!!!!!!!!!!!!!!!!!~             :MMMMMMMMM");printf("\n");
printf("      `+X`'!                    `!!!!!!!!!!!!!!!!!!!!!!`              MMMMMMMMMM");printf("\n");
printf("        X/X!                      `!!!!!!!!!!!!!!!!!!~                MMMMMMMMMM");printf("\n");
printf("        X/`?x                       `!!!!!!!!!!!!!!!                 XMMMMMMMMMM");printf("\n");
printf("        X`/! `+.                       ~!!!!!!!!!!!                  MMMMMMMMMMM");printf("\n");
printf("        X`/!    \".                       `~!!!!!!~                  :MMMMMMMMMMM");printf("\n");
printf("        X/`!      ^%c.                           ~                   MMMMMMMMMMMM",'%');printf("\n");
printf("        X/`!         `~:                       ~                    MMMMMMMMMMMM");printf("\n");
printf("        X`/!             ^=x.                                      MMMMMMMMMMMMM");printf("\n");
printf("        X'/!                  `~+..                               /MMMMMMMMMMMMM");printf("\n");
printf("        X'`!                        `\"~~=::..                    :MMMMMMMMMMMMMM");printf("\n");
printf("        X'`!                                    ``\"\"~~=+::..... xMMMMMMMMMMMMMMM");printf("\n");
printf("        X'/!                                                   XMMMMMMMMMMMMMMMM");printf("\n");
printf("        X'/!                                                  MMMMMMMMMMMMMMMMMM");printf("\n");
printf("        X'`!                                                .MMMMMMMMMMMMMMMMMMM");printf("\n");
printf("        X'`!                                               nMMMMMMMMMMMMMMMMMMMM");printf("\n");
printf("        \"\"'`                                              MMMMMMMMMMMMMMMMMMMMM!");printf("\n");
printf("                                                        .MMMMMMMMMMMMMMMMMMMMM!.");printf("\n");
printf("                                                       XMMMMMMMMMMMMMMMMMMMM!/.>");printf("\n");
printf("                                                      MMMMMMMMMMMMMMMMMMMMM\"/.>/");printf("\n");
printf("                                                    .MMMMMMMMMMMMMMMMMMMMM~/.>//");printf("\n");
main(){
